### ISSUE TITLE
stop event doesnt get triggered at StarblastModding.Client

### ISSUE THREAD

**Issue by officialtroller** [Bhpsngum/starblast-modding#3]
![image](https://github.com/user-attachments/assets/8959ca74-09e6-486d-b116-e0ddb6cd943e)
using a short code that stops the game 2 seconds after start.

**Comment by Bhpsngum** [comment]
interesting that this still somehow happens. I will have a look into it.

**Comment by Bhpsngum** [comment]
Fixed in 1.4.5.

**Comment by officialtroller** [comment]
> Fixed in 1.4.5.

btw did you change anything related to the UI?
Because before the update we were able to use `ship.setUIComponent(data);` to add UI Components but now it just says that `setUIComponent` is not a function.
![image](https://github.com/user-attachments/assets/083d311a-52a4-4736-8586-3c192490a67c)

**Comment by Bhpsngum** [comment]
> btw did you change anything related to the UI? Because before the update we were able to use `ship.setUIComponent(data);` to add UI Components but now it just says that `setUIComponent` is not a function.

yeah they are under the [UIComponentManager](https://bhpsngum.github.io/starblast/starblast-modding/#/latest/UIComponentManager) after the ui rework. There's one for each ship [`ship.ui_components`](https://bhpsngum.github.io/starblast/starblast-modding/#/latest/Ship#ui_components) and a global one to set to every ship [`ShipManager.ui_components`](https://bhpsngum.github.io/starblast/starblast-modding/#/latest/ShipManager#ui_components)

**Comment by officialtroller** [comment]
alright, thanks 👍
